title: "Website"
baseurl: ""
url: "https://patrickziegler.ch"
twitter_username: _patrickziegler
github_username: patrick96

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
