title: "Patrick Ziegler"
baseurl: ""
url: "https://patrickziegler.ch"
twitter_username: _patrickziegler
github_username: patrick96

# Build settings
markdown: kramdown
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light"

plugins:
  - jekyll-feed
